travis:
  secure:
    BINSTAR_TOKEN: audTiomQbApqIpHJeHW+OLq/Dc3LFSYwgRLVyjb9qV3hBYtkff7NLRD/YPZvpedgeL39XJ8e7rVc+2KLWkh6/e8DBIMtCc8m0XtV/7mRdXm3k8+6dea/KnHX1p0DkqKfFiCX0vqwJzFEGz0VdNC8dQ44tcuetHoiqyjV29L5E2HHMEdfr4eEP2ssWgcke5MH+xC2bVtt2IdZgKTOPqeD90WDC+7/hbjMsm2QbifO1h98GGDg6tx4khXhPRcCbDt9d2jmKjAsXD5CNJTt7D0xWZN2UKBPb6PA7SIjA+pGMV02N+mbzM9qW43vGVU9Q63S+xa+A0/6J5aEPO+OeoPrejHoKuwvoWp2B3iblyrQlaI1XnwpW88AamubS8G2w8nV+wOhTa4DqKpIz8+ymLgPNIEQTYeJYrx1Cr7ToQNr9ivE5aFK8L5J6TJzxlCmbvi/4yVhyK300c6zo/u8LXhubaz+0/VI55PE7EiRSA1joMMdoS6CT/FcUUKgAZfDRLwu4qy8X8e4/EQjpKH0YhYjE/dxvCy1eU+2dqrAFF0QejfeT5hJfabq97RIInkWQGFSodPsQp+1DokKBDeBD9jCc185CCxyjwfs6FvCekEhtOXwFEbDn2AegONyySc5EMApC9ChCSVE9lrzrs7x53CRiix9cI0b5AXAYHf0+pM5O+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
