travis:
  secure:
    BINSTAR_TOKEN: ZbxHVTnTUA+S+Yzkq0BJt+tsxv4RTTyxkcAy1yDhgigfb4Qg7TN5M8STnFGZ/zo83vuXt7O+3o91AcrPDKqzw7+SshBmXv8BLYM+NYctz47l41uf4u6M/QFuwjmEKumxsYV79mvhqwRIek8njFrUaN9gv8bsQTYO8RcT/Eer9jfHeWy4Gnt0IbZNwnQvbuRkYtbnFEGTnNJNjdiqiaWLLvpHcvLZcnLMDF8OvlTbWkkwjD0ADuP4bUn29Gc2FfigphL5LrxWLDLX7x0DQjYVornW4SSAFp+O2Eii65eHjXLAgIjSjneyBOKwhfDjNFsFOZKm75SqosEJwrAGkUd96KpFW2b0jCWRvW2Qwe8p7IYYbLR83Xg3TG17SSMMvPcEb4S6QJ5vi3QFl/UfJdO8qT7n7vIyrNukBW9/R/SJmjmT22xqts6njHkC3a4UJgEd6/SdjYv3KNbihI4OdmDIKyaaQmWvWXZBdN5PShBzcZTqhPy/Tcuc6WSMgF7H29ZDOTw/1SUC1F02bf2Cj3GPXZcmd8dimYth4oYzcddkkPYa1Mrdv8pIBhf2QFjpd/D+z+3Ol9j7Vaa3UBWLOUXiRY0N68loJmbVwP7AKIN+HoJSY+dGjMIIW5rJtGwXtDW7w03/PPD6IPdQ7+VMxP8IUK7ndRg0sjcs+iWbp6me85Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
