travis:
  secure:
    BINSTAR_TOKEN: Y1JK4hXUP0u3jARdPglSshgfUctTnV7tV7wxxtGmsjwDjzcxf787Lj25XsloEI6UNXWVk+59bx5DtLJkffQDI6fZngBG9OVy/2ZDz1Jcxiuzh36aTINo2mf+ihPz+7Nu/EQPYe9ro/eiN/I5HvMLDFcJH/Q0gcwOpscLVxrSYoFzd16Z981okYgqr8t1LjwVVuz84S5eH3tmW9TxPsWp9ZAhBhweOdtBl+y61Gt1CcnIwo68CGMqzlzFtDu9rxvLRcn7nbuALo/5wFUJzsUwkiMbEx6PYTrG3lkXRmgHNflAIbcTPxjMYKkzK5iYT2cNNJL0l6hFeiRCNOxq7QRukr+5kaY3roQdoycehpiEE3ND/WXhJYlbx0/vVE4C4Mn76/RmO+oUyVxu5EkFCtgjOYFjCjswJOzu8XbeOoTAa6yEr/v6Pj9PtLslU/AnY3fneLmVlc7q1WxWAlE8pcQB3CE/JNeo/2mEdUB3ISa29/hZsNOerdNrKeOJL6UwdIiAxKDJHX4GwNc3geX3abo8AKyXhxHQ+lgUyoH9P4c1vdKZ8m4dd6n930RVGvolh27PxPPWTLa++424jFfRWKBoHwI3NC6rc2x5LpdqJLOtPZHERNHQIKC5WN80ThKts98wFBKnS2IydaF4A9WltvTnvoJhapohlnv0klaejEFMcck=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
